### ISSUE TITLE
Tasks for next release

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-deny#460]
Tracking issue for things I need to do before publishing a new release

- [x] Finish testing the feature banning, and the big change to krates introduced in #434 
  - [x] Publish new krates version once I'm satisfied the graph is correct including for niche areas https://github.com/EmbarkStudios/krates/pull/42
  - [x] Ensure crate banning can encompass `default` features. This should resolve #206 and close #347 
  - [x] Add tests for `features.allow` and `features.exact`
  - [x] Ensure the duplicate dot graphs still look good with features being added. Could also have an option to ignore features in the duplicate graph.
- [x] Convert most/all tests to use the snapshot testing that was introduced in #434.
- [x] Add options for limiting the depth for which features are reported, as well as for crates for the inclusion graphs that are printed in the output. The graphs can be pretty intimidating on large projects so allowing configs to limit them and then opt-in to greater depth if desired could be nice #466
- [x] We have error codes, but don't use them for anything, it would be good to add top level options to override defaults, just as clippy has. #464 

```
    -W --warn OPT       Set lint warnings
    -A --allow OPT      Set lint allowed
    -D --deny OPT       Set lint denied
    -F --forbid OPT     Set lint forbidden
```
